# Generated by Django 5.2.17 on 2026-09-13 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMOBILIARIA', 'Imobiliária'), ('AUTONOMO', 'Corretor autônomo')], max_length=20)),
                ('razao_social_ou_nome', models.CharField(max_length=200, verbose_name='razão social ou nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('creci', models.CharField(max_length=20, verbose_name='CRECI')),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='empresas/logomarcas/')),
                ('descricao', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cidades_atuacao', models.ManyToManyField(blank=True, related_name='empresas_atuantes', to='localizacao.cidade')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='core.endereco')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razao_social_ou_nome'],
            },
        ),
    ]
