# Generated by Django 5.2.17 on 2026-09-14 00:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logomarca',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logomarcas/', validators=[core.validators.validar_imagem]),
        ),
    ]
