# Generated by Django 5.2.17 on 2026-09-21 01:14

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_endereco_latitude_endereco_longitude'),
        ('empresas', '0002_alter_empresa_logomarca'),
        ('imoveis', '0001_initial'),
        ('proprietarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('finalidade', models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel'), ('VENDA_E_ALUGUEL', 'Venda e aluguel')], max_length=20)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caracteristicas', models.ManyToManyField(blank=True, related_name='imoveis', to='imoveis.caracteristica')),
                ('corretor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis_responsavel', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imovel', to='core.endereco')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='proprietarios.proprietario')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/fotos/', validators=[core.validators.validar_imagem])),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('capa', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'foto do imóvel',
                'verbose_name_plural': 'fotos do imóvel',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='imovel',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='codigo_unico_por_empresa', violation_error_message='Já existe um imóvel com esse código nesta empresa.'),
        ),
        migrations.AddConstraint(
            model_name='fotoimovel',
            constraint=models.UniqueConstraint(condition=models.Q(('capa', True)), fields=('imovel',), name='uma_capa_por_imovel', violation_error_message='Este imóvel já tem uma foto de capa.'),
        ),
    ]
