# Generated by Django 5.2.17 on 2026-09-14 00:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apresentacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='creci',
            field=models.CharField(blank=True, max_length=20, verbose_name='CRECI'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='corretores/fotos/', validators=[core.validators.validar_imagem]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
