# Generated by Django 5.2.17 on 2026-09-21 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_alter_empresa_logomarca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa física'), ('JURIDICA', 'Pessoa jurídica')], max_length=10)),
                ('nome_razao_social', models.CharField(max_length=200, verbose_name='nome ou razão social')),
                ('documento', models.CharField(max_length=18, verbose_name='CPF ou CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'proprietário',
                'verbose_name_plural': 'proprietários',
                'ordering': ['nome_razao_social'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'documento'), name='documento_unico_por_empresa', violation_error_message='Já existe um proprietário com esse documento nesta empresa.')],
            },
        ),
    ]
